version: '3.8'
name: resort
services:
  database:
    container_name: resort-database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=resort
      - MYSQL_TCP_PORT=3306
    ports:
      - "3309:3306"
    build: ./database
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  backend:
    container_name: resort-backend
    environment:
      - NODE_ENV=compose
    ports:
      - "3020:3000"
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
  frontend:
    container_name: resort-frontend
    ports:
      - "3012:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile.compose
  localstack:
    container_name: resort-localstack-compose
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    image: localstack/localstack
    volumes:
      - s3localdata:/var/lib/localstack
volumes:
  s3localdata:
  resortdata:


